services:
  db:
    image: postgres:16-alpine
    container_name: project8-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - project8-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project8-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    expose:
      - "8000"
    networks:
      - project8-net


volumes:
  pgdata:

networks:
  project8-net:
    driver: bridge
